services:
  postgres:
    image: postgres:13
    container_name: medusa_postgres
    environment:
      POSTGRES_DB: medusa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: